### ISSUE TITLE
Why body size  is only 16MiB?

### ISSUE THREAD

**Issue by Amirkin** [VKCOM/kittenhouse#11]
Hi!

What if i need more?

Thanks.

**Comment by YuriyNasretdinov** [comment]
1. The maximum size of the per-table in-memory buffer is 16 Mb to limit max memory consumption in case ClickHouse is struggling to keep up with the amount of data written and you're ok with losing the stuff that you're writing (e.g. it's better to just drop extra error logs if you are already writing too much).
2. For the persistent mode the actual limit is even lower, it's just 1 MiB per chunk. In my benchmarks I didn't see any performance improvements when writing to Buffer tables in bigger chunks so in order to save memory in the receiving side I chose even smaller chunks.

Answering your question in terms of what to do if you want bigger chunks: I would advise against writing so big rows into ClickHouse. You would get much better performance if you write more rows that are smaller than 1 huge row because ClickHouse reads columns in big chunks and you'll probably consume a lot of ClickHouse memory if your rows are 16 MiB each.

If you still want to insert such big chunks, there is no real need to use kittenhouse in this case: just insert directly into ClickHouse Buffer table instead. Using kittenhouse (and kittenhouse --reverse) only makes sense when you have a lot of small rows that come from many servers. If you only have 1 server and you already have big chunks just INSERT data directly into ClickHouse, it will be more efficient that way.

**Comment by Amirkin** [comment]
Thank you
