### ISSUE TITLE
persistent data ordering

### ISSUE THREAD

**Issue by forward32** [VKCOM/kittenhouse#6]
Hi!

Imagine the following situation:
- we are writing data to kittenhouse to table X with `persistent=1`;
- at some moment clickhouse turned-off and some piece of data for table X not passed to it (still on disk);
- next we simultaneously turning-on clickhouse and my app which executes `select * from X`;

Am I right saying in that case my app potentially could receive not full data (without piece of data stored on disk and not passed to clickhouse yet)?

Thanks a lot!

**Comment by YuriyNasretdinov** [comment]
You may receive data not exactly in the order that it was inserted, in part because kittenhouse does INSERTs in chunks and only reads up to 1 MiB (my default) from each file before going to the next one. So yes, this is correct. Parameter `persistent=1` only guarantees that data will be eventually delivered, without any specific order

**Comment by forward32** [comment]
Thank you, closed.
